export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const TOGGLE_LIKED = 'TOGGLE_LIKED';
export const SET_CURRENT_DIALOG = 'SET_CURRENT_DIALOG';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_USERS = 'GET_USERS';
export const TOGGLE_FOLLOWING = 'TOGGLE_FOLLOWING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';