// App types
export const appTypes = {
    INITIALIZED_SUCCESS: 'INITIALIZED_SUCCESS'
};

// Profile types
export const profileTypes = {
    SET_PROFILE: 'SET_PROFILE',
    ADD_POST: 'ADD_POST',
    DELETE_POST: 'DELETE_POST',
    TOGGLE_LIKED: 'TOGGLE_LIKED',
    GET_STATUS: 'GET_STATUS',
    UPDATE_STATUS: 'UPDATE_STATUS',
    TOGGLE_PROFILE_FETCHING: 'TOGGLE_PROFILE_FETCHING',
    SET_PHOTO: 'SET_PHOTO'
};

// Dialogs types
export const dialogsTypes = {
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    GET_DIALOGS_SUCCESS: 'GET_DIALOGS_SUCCESS',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
    SET_CURRENT_ID: 'SET_CURRENT_ID',
};

// Users types
export const usersTypes = {
    GET_USERS: 'GET_USERS',
    TOGGLE_FOLLOWING: 'TOGGLE_FOLLOWING',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    TOGGLE_FETCHING: 'TOGGLE_FETCHING',
    DISABLE_BUTTON: 'DISABLE_BUTTON'
};

// Auth types
export const authTypes = {
    SET_AUTH: 'SET_AUTH',
    LOGOUT: 'LOGOUT'
};


