// App types
export const INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS';

export interface InitializedSuccessActionType {
    type: typeof INITIALIZED_SUCCESS
}

// Profile types
export const profileTypes = {
    SET_PROFILE: 'SET_PROFILE',
    ADD_POST: 'ADD_POST',
    DELETE_POST: 'DELETE_POST',
    TOGGLE_LIKED: 'TOGGLE_LIKED',
    GET_STATUS: 'GET_STATUS',
    UPDATE_STATUS: 'UPDATE_STATUS',
    TOGGLE_PROFILE_FETCHING: 'TOGGLE_PROFILE_FETCHING',
    SET_PHOTO: 'SET_PHOTO'
};

// Dialogs types
export const dialogsTypes = {
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    GET_DIALOGS_SUCCESS: 'GET_DIALOGS_SUCCESS',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING',
    SET_CURRENT_ID: 'SET_CURRENT_ID',
    TOGGLE_SHOW_MODAL: 'TOGGLE_SHOW_MODAL',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SHOW_SENT_MESSAGE_SUCCESS_MODAL: 'SHOW_SENT_MESSAGE_SUCCESS_MODAL',
    HIDE_SENT_MESSAGE_SUCCESS_MODAL: 'HIDE_SENT_MESSAGE_SUCCESS_MODAL',
    DELETE_MESSAGES: 'DELETE_MESSAGES'
};

// Users types
export const usersTypes = {
    GET_USERS: 'GET_USERS',
    TOGGLE_FOLLOWING: 'TOGGLE_FOLLOWING',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    TOGGLE_FETCHING: 'TOGGLE_FETCHING',
    DISABLE_BUTTON: 'DISABLE_BUTTON'
};

// Auth types
export const authTypes = {
    SET_AUTH: 'SET_AUTH',
    LOGOUT: 'LOGOUT'
};

export type SetAuthActionType = {
    type: typeof authTypes.SET_AUTH,
    payload: any
}

export type AppActionTypes = InitializedSuccessActionType | SetAuthActionType
